/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'grafont\'">' + entity + '</span>' + html;
	}
	var icons = {
		'gf-angle-double-down': '&#xe900;',
		'gf-angle-double-left': '&#xe901;',
		'gf-angle-double-right': '&#xe902;',
		'gf-angle-double-up': '&#xe903;',
		'gf-angle-down': '&#xe904;',
		'gf-angle-left': '&#xe905;',
		'gf-angle-right': '&#xe906;',
		'gf-angle-up': '&#xe907;',
		'gf-arrow-down': '&#xe908;',
		'gf-arrow-left': '&#xe909;',
		'gf-arrow-right': '&#xe90a;',
		'gf-arrow-up': '&#xe90b;',
		'gf-at': '&#xe90c;',
		'gf-bars': '&#xe90d;',
		'gf-bell': '&#xe90e;',
		'gf-bookmark': '&#xe90f;',
		'gf-border-all': '&#xe910;',
		'gf-building': '&#xe911;',
		'gf-calendar': '&#xe912;',
		'gf-check': '&#xe913;',
		'gf-check-circle': '&#xe914;',
		'gf-check-double': '&#xe915;',
		'gf-check-square': '&#xe916;',
		'gf-clock': '&#xe917;',
		'gf-cog': '&#xe918;',
		'gf-cogs': '&#xe919;',
		'gf-comment': '&#xe91a;',
		'gf-comment-dots': '&#xe91b;',
		'gf-comments': '&#xe91c;',
		'gf-credit-card': '&#xe91d;',
		'gf-desktop-solid': '&#xe91e;',
		'gf-digg': '&#xe91f;',
		'gf-download': '&#xe920;',
		'gf-edit': '&#xe921;',
		'gf-envelope': '&#xe922;',
		'gf-eye': '&#xe923;',
		'gf-facebook': '&#xe924;',
		'gf-file-alt': '&#xe925;',
		'gf-file-archive': '&#xe926;',
		'gf-file-invoice': '&#xe927;',
		'gf-github': '&#xe928;',
		'gf-google': '&#xe929;',
		'gf-google-plus': '&#xe92a;',
		'gf-hands-helping': '&#xe92b;',
		'gf-heart': '&#xe92c;',
		'gf-heart-o': '&#xe92d;',
		'gf-home': '&#xe92e;',
		'gf-info': '&#xe92f;',
		'gf-instagram': '&#xe930;',
		'gf-laptop': '&#xe931;',
		'gf-line': '&#xe932;',
		'gf-linkedin': '&#xe933;',
		'gf-list': '&#xe934;',
		'gf-lock': '&#xe935;',
		'gf-logout': '&#xe936;',
		'gf-mail-bulk': '&#xe937;',
		'gf-map-marker': '&#xe938;',
		'gf-minus': '&#xe939;',
		'gf-money': '&#xe93a;',
		'gf-more': '&#xe93b;',
		'gf-patch-check': '&#xe93c;',
		'gf-patch-check-fill': '&#xe93d;',
		'gf-phone': '&#xe93e;',
		'gf-pinterest': '&#xe93f;',
		'gf-play': '&#xe940;',
		'gf-plus': '&#xe941;',
		'gf-power-off': '&#xe942;',
		'gf-question': '&#xe943;',
		'gf-reddit': '&#xe944;',
		'gf-rocket': '&#xe945;',
		'gf-ruler': '&#xe946;',
		'gf-search': '&#xe947;',
		'gf-share': '&#xe948;',
		'gf-shopping-cart': '&#xe949;',
		'gf-sort': '&#xe94a;',
		'gf-sort-alpha-down': '&#xe94b;',
		'gf-sort-alpha-down-alt': '&#xe94c;',
		'gf-sort-alpha-up': '&#xe94d;',
		'gf-sort-alpha-up-alt': '&#xe94e;',
		'gf-sort-amount-down': '&#xe94f;',
		'gf-sort-amount-down-alt': '&#xe950;',
		'gf-sort-amount-up': '&#xe951;',
		'gf-sort-amount-up-alt': '&#xe952;',
		'gf-sort-down': '&#xe953;',
		'gf-sort-numeric-down': '&#xe954;',
		'gf-sort-numeric-down-alt': '&#xe955;',
		'gf-sort-numeric-up': '&#xe956;',
		'gf-sort-numeric-up-alt': '&#xe957;',
		'gf-sort-up': '&#xe958;',
		'gf-star': '&#xe959;',
		'gf-star-half': '&#xe95a;',
		'gf-star-half-alt': '&#xe95b;',
		'gf-store': '&#xe95c;',
		'gf-store-alt': '&#xe95d;',
		'gf-store-alt-slash': '&#xe95e;',
		'gf-store-slash': '&#xe95f;',
		'gf-tag': '&#xe960;',
		'gf-tags': '&#xe961;',
		'gf-telegram': '&#xe962;',
		'gf-th': '&#xe963;',
		'gf-times': '&#xe964;',
		'gf-times-circle': '&#xe965;',
		'gf-trash': '&#xe966;',
		'gf-truck': '&#xe967;',
		'gf-tumblr': '&#xe968;',
		'gf-twitter': '&#xe969;',
		'gf-unlock': '&#xe96a;',
		'gf-user': '&#xe96b;',
		'gf-user-alt': '&#xe96c;',
		'gf-user-alt-slash': '&#xe96d;',
		'gf-user-astronaut': '&#xe96e;',
		'gf-user-check': '&#xe96f;',
		'gf-user-circle': '&#xe970;',
		'gf-user-clock': '&#xe971;',
		'gf-user-cog': '&#xe972;',
		'gf-user-edit': '&#xe973;',
		'gf-user-friends': '&#xe974;',
		'gf-user-graduate': '&#xe975;',
		'gf-user-injured': '&#xe976;',
		'gf-user-lock': '&#xe977;',
		'gf-user-md': '&#xe978;',
		'gf-user-minus': '&#xe979;',
		'gf-user-ninja': '&#xe97a;',
		'gf-user-nurse': '&#xe97b;',
		'gf-user-plus': '&#xe97c;',
		'gf-users': '&#xe97d;',
		'gf-users-cog': '&#xe97e;',
		'gf-user-secret': '&#xe97f;',
		'gf-user-shield': '&#xe980;',
		'gf-user-slash': '&#xe981;',
		'gf-users-slash': '&#xe982;',
		'gf-user-tag': '&#xe983;',
		'gf-user-tie': '&#xe984;',
		'gf-user-times': '&#xe985;',
		'gf-viadeo': '&#xe986;',
		'gf-viber': '&#xe987;',
		'gf-video': '&#xe988;',
		'gf-vk': '&#xe989;',
		'gf-whatsapp': '&#xe98a;',
		'gf-window-close': '&#xe98b;',
		'gf-youtube': '&#xe98c;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/gf-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
